RyanFoerster/sonar-front

package-lock.json, src/app/admin/sepa-validation/sepa-validation.component.html, src/app/admin/sepa-validation/sepa-validation.component.ts, src/app/shared/entities/virement-sepa.entity.ts, src/app/shared/services/users.service.ts, src/app/shared/services/virement-sepa.service.ts, src/app/users/home/home-group/home-group.component.html, src/app/users/home/home-group/home-group.component.ts, src/app/users/home/home-group/project-account/project-account.component.html, src/app/users/home/home-group/project-account/project-account.component.ts, src/app/users/profile/profile.component.html
- Refactored the SEPA validation component's HTML for improved layout and user experience.
- Introduced PDF viewing functionality for invoices within the SEPA validation process.
- Updated the SEPA service to handle rejection reasons for transactions.
- Enhanced user interface elements for better accessibility and interaction.
- Added support for additional file types in the upload component.
- Improved data handling in the user profile component to display relevant user information.
=> REF: Enhance SEPA validation component and update related services

src/app/shared/entities/virement-sepa.entity.ts, src/app/users/home/home-group/project-account/project-account.component.html
- Added 'PAID' status to the VirementSepaEntity interface.
- Updated HTML templates to reflect the new 'PAID' status in various components.
- Enhanced status display logic to include 'Payé' for the 'PAID' status.
- Improved visual indicators for transaction statuses in the user interface.
=> feat: Extend virement status options and update UI accordingly

src/app/users/home/home-group/home-group.component.html
- Implemented conditional rendering for the 'facturation' link in the home group component based on the user's role.
- Enhanced user interface by ensuring that only users with the 'ADMIN' role can see the link, improving security and user experience.
=> feat: Add conditional rendering for admin link in home group component

src/app/users/home/home-group/home-group.routes.ts
- Integrated adminGuard to the facturation routes, ensuring that only users with admin privileges can access these components.
- Enhanced security by restricting access to sensitive areas of the application based on user roles.
=> feat: Add admin guard to facturation routes in home group component

src/app/users/home/home-group/project-account/project-account.component.html, src/app/users/home/home-group/project-account/project-account.component.ts
- Updated HTML templates to improve layout and styling, including better alignment and spacing for buttons and form elements.
- Added icons to buttons for a more intuitive user experience.
- Enhanced form structure with clearer labels and improved accessibility.
- Implemented sorting for virement entries by date, ensuring the most recent transactions are displayed first.
- Streamlined the import statements for better organization and clarity.
- Improved error handling display for user feedback during form submissions.
=> feat: Enhance ProjectAccountComponent UI and form handling

src/app/users/home/home-group/project-account/project-account.component.ts
- Streamlined the handling of asynchronous operations by replacing async/await with RxJS forkJoin for fetching transactions and virements, improving performance and readability.
- Updated import statements for better organization and clarity.
- Enhanced loading state management by adjusting delay times, ensuring a smoother user experience during data fetching.
- Improved error handling by converting subscription to a promise, allowing for better control over asynchronous flows.
=> refactor: Optimize asynchronous operations in ProjectAccountComponent

src/app/header/header.component.html, src/app/shared/services/compte-groupe.service.ts, src/app/users/home/account-component/account-component.component.html, src/app/users/home/home-group/home-group.component.html, src/app/users/home/home-group/home-group.component.ts, src/app/users/home/home-group/project-account/project-account.component.html, src/app/users/home/home-group/project-account/project-account.component.ts, src/app/users/profile/profile.component.css
- Updated header component to improve user notifications and profile access, including better handling of invitations.
- Refactored account component to enhance project navigation and visual feedback with hover effects.
- Improved home group component by adding a dialog for viewing project members, enhancing user interaction.
- Optimized project account component with sorted account lists for better usability and streamlined file upload handling.
- Updated CSS for profile component to refresh background image, improving visual appeal.
- Enhanced service layer to include member retrieval functionality, supporting new UI features.
=> feat: Enhance user interface and functionality in various components

src/app/shared/services/auth.service.ts, src/app/users/home/home-group/project-account/project-account.component.html, src/app/users/home/home-group/project-account/project-account.component.ts
- Added input fields for filtering principal and group accounts, improving user experience when searching for accounts.
- Updated form layout and styling for better accessibility and visual appeal, including consistent spacing and rounded inputs.
- Refactored the create virement functionality to streamline the handling of amounts and improve clarity in the code.
- Enhanced error message display for better user feedback during form submissions.
- Improved sorting logic for account lists, ensuring a more intuitive user interface.
=> feat: Enhance ProjectAccountComponent with filtering and UI improvements

src/app/shared/components/notifications/notifications.component.ts, src/app/users/home/home-group/membership/membership.component.ts
- Updated NotificationsComponent to filter GROUP_INVITATION notifications with defined groupId, improving data integrity and handling.
- Refactored MembershipComponent to include additional icons for better user interface and interaction, enhancing visual feedback for users.
=> refactor: Enhance notifications handling and UI components

src/app/auth/forgotten-password/forgotten-password.component.html, src/app/auth/forgotten-password/forgotten-password.component.ts, src/app/auth/login/login.component.html, src/app/auth/login/login.component.ts, src/app/auth/register/register.component.html, src/app/auth/register/register.component.ts, src/app/shared/services/notification.service.ts, src/app/users/home/home-group/facturation/new-quote/new-quote.component.html, tailwind.config.js
- Updated the LoginComponent and RegisterComponent to improve user experience with better form validation and error handling.
- Refactored the forgotten password flow, including UI updates for clarity and improved user feedback.
- Enhanced Tailwind CSS configuration to include new color utilities for better styling options.
- Streamlined notification handling in the NotificationService to ensure proper polling based on user authentication state.
- Improved the NewQuoteComponent with better client selection and form handling, ensuring a smoother user experience.
=> feat: Enhance authentication and user management components

src/app/auth/login/login.component.ts, src/app/shared/guards/activated-user.guard.ts, src/app/shared/interceptors/auth.interceptor.ts, src/app/shared/services/auth.service.ts, src/app/users/home/home-group/facturation/facturation.component.ts, src/app/users/home/home-group/home-group.component.ts, src/app/users/home/home-group/project-account/project-account.component.ts, src/app/users/home/home.component.html, src/environments/environment.development.ts, src/environments/environment.ts
- Replaced the authService login method with usersService signIn in LoginComponent for better separation of concerns.
- Improved token management by adding setTokens method in AuthService to handle access and refresh tokens.
- Updated activatedUserGuard to check authentication status and refresh tokens if necessary, enhancing security.
- Refactored auth.interceptor to streamline header management and remove hardcoded API keys.
- Made UI adjustments in home.component.html for better responsiveness and user experience.
- Cleaned up console logs in ProjectAccountComponent to reduce clutter and improve code readability.
=> refactor: Enhance authentication flow and user experience

components.json, src/app/shared/dtos/invoice.dto.ts, src/app/shared/entities/invoice.entity.ts, src/app/shared/services/invoice.service.ts, src/app/shared/services/pdf-generator.service.ts, src/app/users/home/home-group/facturation/facturation.component.html, src/app/users/home/home-group/facturation/facturation.component.ts, src/app/users/home/home-group/facturation/new-credit-note/new-credit-note.component.html, src/app/users/home/home-group/facturation/new-credit-note/new-credit-note.component.spec.ts, src/app/users/home/home-group/facturation/new-credit-note/new-credit-note.component.ts, src/app/users/home/home-group/facturation/new-quote/new-quote.component.html, src/app/users/home/home-group/facturation/new-quote/new-quote.component.ts, src/environments/environment.development.ts
- Added new components and services for handling invoices and credit notes, including PdfGeneratorService for PDF generation.
- Created a new InvoiceDto interface to standardize invoice data structure.
- Updated existing invoice entity to change payment_deadline type to Date for better date handling.
- Enhanced the facturation component to support credit note creation and improved pagination for document management.
- Introduced a new credit note component with form validation and client management features.
- Updated HTML templates to improve user interaction and added new buttons for creating credit notes.
- Refactored service methods to streamline invoice and credit note creation processes.
These changes significantly enhance the billing process and user experience in managing invoices …
=> feat: Introduce invoice and credit note management enhancements

src/environments/environment.ts
- Updated the application version in environment.ts from 1.0.2 to 1.0.3 to reflect the latest changes and ensure consistency across deployments.
=> chore: Bump app version to 1.0.3 in environment configuration

src/environments/environment.development.ts, src/environments/environment.ts
- Updated the application version in environment.development.ts from 1.0.3 to 1.0.4 to reflect the latest changes and ensure version consistency
=> chore: Bump app version to 1.0.4 in environment configuration

src/app/app.routes.ts, src/app/shared/guards/is-logged.guard.ts, src/environments/environment.development.ts, src/environments/environment.ts
- Prevent logged-in users from accessing login, register, and forgotten password pages
- Import and apply isLoggedInGuard to relevant authentication routes
- Bump app version to 0.5.2
=> 🔒 feat: Add isLoggedInGuard to authentication routes

src/app/app.component.ts, src/app/shared/dtos/beneficiary.dto.ts, src/app/shared/entities/beneficiary.entity.ts, src/app/shared/services/beneficiary.service.spec.ts, src/app/shared/services/beneficiary.service.ts, src/app/users/home/home-group/project-account/project-account.component.html, src/app/users/home/home-group/project-account/project-account.component.ts, src/app/users/home/home.component.html, src/environments/environment.development.ts, src/environments/environment.ts
- Implemented beneficiary selection dropdown with search functionality
- Added methods to load, filter, and select beneficiaries dynamically
- Updated virement SEPA form to auto-populate beneficiary details
- Improved UI with responsive dropdown and search input
- Added keyboard and click-outside event handling for dropdown
- Bumped app version to 0.5.4
=> ✨ feat: Add beneficiary dropdown and management in project account

src/app/shared/components/multi-account-select/multi-account-select.component.html, src/app/shared/components/multi-account-select/multi-account-select.component.spec.ts, src/app/shared/components/multi-account-select/multi-account-select.component.ts, src/app/users/home/home-group/project-account/project-account.component.html, src/app/users/home/home-group/project-account/project-account.component.ts, src/environments/environment.development.ts, src/environments/environment.ts
- Replaced dropdown selects with a more intuitive project selection interface
- Added search functionality to filter projects across individual and group types
- Implemented dynamic project selection with add/remove capabilities
- Updated transaction form to support multiple recipient types
- Improved visual design with color-coded selections and hover states
- Bumped app version to 0.5.5
=> ✨ feat: Redesign project selection with enhanced UX and interaction

src/app/shared/services/client.service.ts, src/app/users/home/home-group/facturation/new-quote/new-quote.component.ts, src/app/users/home/home-group/home-group.component.ts
- Updated BCE check endpoint in client service
- Sanitized company number input by removing spaces and dots
- Removed console.log statements from home group component
- Cleaned up unused import in new quote component
=> 🔧 chore: Optimize client service and remove debug logs

docker-compose.yaml, src/environments/environment.ts
- add traefik labels for HTTP and HTTPS routing
- set up HTTPS redirect middleware
- configure traefik network for external use
♻️ refactor(environment): update API URL for production
- change API_URL to 'backend.sonarartists.be' for correct endpoint access
=> 📦 build(docker): configure traefik for sonar-front service

src/app/admin/sepa-validation/sepa-validation.component.ts, src/app/shared/services/quote.service.ts, src/app/shared/services/users.service.ts, src/app/shared/services/virement-sepa.service.ts, src/app/users/home/home-group/facturation/facturation.component.html, src/app/users/home/home-group/facturation/facturation.component.ts, src/app/users/home/home-group/facturation/new-quote/new-quote.component.html, src/app/users/home/home-group/facturation/new-quote/new-quote.component.ts, src/app/users/home/home-group/membership/membership.component.html, src/app/users/home/home-group/membership/membership.component.ts, src/app/users/home/home-group/project-account/project-account.component.html, src/environments/environment.development.ts, src/environments/environment.ts
- Enhanced quote creation with optional file attachment (PDF only)
- Implemented drag-and-drop and file selection for quote attachments
- Added comment section to quotes with UI for displaying comments
- Updated quote service to support file upload via FormData
- Improved quote form with new comment and file upload fields
- Added file validation and preview functionality
=> ✨ feat: Add file upload and comment support for quotes

src/app/users/home/home.component.html, src/app/users/home/home.component.ts
- Introduced `isLoadingAccounts` signal to track account loading status
- Added loading message in home component template when accounts are being fetched
- Updated admin data loading method to set loading state before and after data retrieval
=> ✨ feat: Add loading state for account retrieval

src/app/users/home/home-group/facturation/new-quote/new-quote.component.html, src/app/users/home/home-group/facturation/new-quote/new-quote.component.ts
- Introduced `isLoadingQuote` signal to track quote creation loading status
- Updated submit button to display loading spinner when quote is being generated
- Implemented loading state management in quote creation service method
=> ✨ feat: Add loading state for quote generation

src/app/header/header.component.html, src/app/header/header.component.ts, src/app/quote-decision/quote-decision.component.html, src/app/quote-decision/quote-decision.component.ts, src/app/shared/dtos/quote.dto.ts, src/app/shared/entities/quote.entity.ts, src/app/users/home/home-group/facturation/new-quote/new-quote.component.ts, src/environments/environment.development.ts, src/environments/environment.ts
- Added responsive design for header component with mobile-friendly layout
- Introduced development status alert with warning icon and informative message
- Updated header component to use responsive classes and improve mobile view
- Added new fields to quote-related DTOs and entities for creator information
- Temporarily disabled access control in quote decision component
- Bumped app version to 0.5.10
=> ✨ feat: Add development status alert and improve header responsiveness

src/app/users/home/home.component.html, src/environments/environment.development.ts, src/environments/environment.ts
- Added informative red banner for mobile and desktop views
- Warns users about potential platform slowdown or unavailability during weekend updates
- Updated app version to 0.5.14
=> ✨ feat: Add maintenance weekend warning banner to home component

src/app/quote-decision/quote-decision.component.html, src/app/users/home/home.component.ts, src/environments/environment.development.ts, src/environments/environment.staging.ts, src/environments/environment.ts
- Mettre à jour la version de l'application dans les environnements de développement, de staging et de production
- Mise à jour mineure pour refléter les dernières modifications
- Correction de libellé dans le composant de décision de devis (Statut Groupe -> Statut Projet)
- Ajout du module FormsModule dans le composant Home
=> 🔧 chore(version): Bump application version to 0.6.4

src/app/admin/push-notifications/push-notifications.component.html, src/app/admin/push-notifications/push-notifications.component.ts, src/app/app.config.ts, src/app/services/push-notification.service.ts, src/environments/environment.development.ts, src/environments/environment.staging.ts, src/environments/environment.ts
- Mettre à jour la configuration du Service Worker pour activer/désactiver les notifications en fonction du mode de développement
- Ajouter des fonctionnalités pour gérer l'abonnement et le désabonnement aux notifications
- Intégrer des options avancées pour personnaliser le comportement des notifications
- Mettre à jour la version de l'application à 0.6.11 dans tous les environnements
=> ✨ feat(push-notifications): Améliorer la gestion des notifications push
